### PR TITLE
feat: Add MSTest and remove GTest

### PR DESCRIPTION
**Pull request by divy9881**
Microsoft Azure pipeline doesn't have GTest test adapter, hence are tests were not running before, for now, there is no solution to this problem, so I switched Microsoft test framework for CPP.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@divy9881 what if we setup Linux CI in future? Is MSTest available on Linux? I want a cross-platform C/C++ test framework that runs on all OSes: Windows, Linux (and also Mac ideally). Because Casbin-CPP is cross-platform. So I need to have a cross-platform test framework to run all test cases.

**Comment by divy9881** [comment]
> @divy9881 what if we setup Linux CI in future? Is MSTest available on Linux? I want a cross-platform C/C++ test framework that runs on all OSes: Windows, Linux (and also Mac ideally). Because Casbin-CPP is cross-platform. So I need to have a cross-platform test framework to run all test cases.

Okay so after a lot of exploration on CPP project's working environments, I have come to a conclusion that there are some options:

1. `MSTest` as test framework and `Azure Pipeline` for `windows` and `travis CI` for `Unix` :
-> In this env, we test our library on VS C++ (windows) and build on both the platforms

2. `GTest` as test framework and `Azure Pipeline` for `windows` and `travis CI` for `Unix`(Linux and MacOS) :
-> In this env, we test our library on just Unix platform and build on both the platforms.

3. `GTest` as test framework and `AppVeyor` for `windows` and `travis CI` for `Unix` :
-> In this env, we test and build our library on both the platforms, but the build process becomes quite complicated as VS C++ platform provides GTest adapter by default but for linux systems we may have to include GTest library in our core library.

I think either of this options works fine, as our library doesn't include any OS specific operations like communication protocol related use-cases or multi-processing kind of stuffs, so testing our library on one of the platforms is quite okay in our use-case.

But instead testing and building the code on both the platforms, what we can do is test on windows and build on both the platforms.

**Comment by divy9881** [comment]
@hsluoyz, let me know your thoughts on this?

**Comment by hsluoyz** [comment]
> In this env, we test and build our library on both the platforms, but the build process becomes quite complicated as VS C++ platform provides GTest adapter by default but for linux systems we may have to include GTest library in our core library.

If `Microsoft Azure pipeline doesn't have GTest test adapter` is resolved and we go option 2, will it be as complicated as you described in option 3?

Can you raise an issue to Azure Pipeline's maintainers to solve the `Microsoft Azure pipeline doesn't have GTest test adapter` issue?

**Comment by divy9881** [comment]
> If Microsoft Azure pipeline doesn't have GTest test adapter is resolved and we go option 2, will it be as complicated as you described in option 3?

Yes, indeed.

**Comment by hsluoyz** [comment]
Then we go with option 1 for now.

**Comment by divy9881** [comment]
https://developercommunity.visualstudio.com/content/problem/1086341/gtest-test-adapter-cannot-discover-the-tests.html
I have raised the issue.

**Pull request merged**
