### PR TITLE
test: update the benchmark tests

### PR DESCRIPTION
**Pull request by JalinWang**
Part of: https://github.com/casbin/casbin/issues/1049

Command:
```bash
mkdir build & cd build
cmake .. -DCMAKE_BUILD_TYPE:STRING=Release -DINTENSIVE_BENCHMARK:BOOL=ON
cmake --build . --config Release
```

Notes:
1. Without the support for `KeyMatch4` and `ABAC` model in `Casbin-cpp` , some test cases are missing. 

2. As for `BenchmarkCachedRBACModelMediumParallel`, there are no routines in C++ so it is not enabled.
Implementation in Golang version:
image
image

3. I have tested on Windows, WSL, and Ubuntu. However, I encounter some errors triggered by the existing codes(only works well on Windows). I'm not sure whether it should be cared about or not.
WSL:
image
Ubuntu, compiled locally:
image
Ubuntu, compiled on WSL:
image
Caused by:
```cpp
static const std::vector<std::vector<std::string>> s_policy = {{"alice", "data1", "read"}, {"bob", "data2", "write"}};

static bool rawEnforce(const std::string& sub, const std::string& obj, const std::string& act) {
    for (const auto& rule : s_policy) {
        if (rule[0] == sub && rule[1] == obj && rule[2] == act)
            return true;
    }
    return false;
}

static void BenchmarkRaw(benchmark::State& state) {
    for (auto _ : state) rawEnforce("alice", "data1", "read");
}

BENCHMARK(BenchmarkRaw);
```
4.  In `BenchmarkRBACModelSizesLarge`, it takes nearly an hour to construct the test case
```cpp
    for (int i = 0; i < 100000; ++i) {
        e.AddGroupingPolicy({"user-has-a-very-long-name-" + std::to_string(i), "group-has-a-very-long-name-" + std::to_string(i % num_roles)});
    }
```
Any way to speed up?
Result on my Windows PC:(intel i7- 1170K) with `O2` flags
```
BenchmarkRaw                                   0.249 ns        0.250 ns   1000000000
BenchmarkBasicModel                            11225 ns        11230 ns        64000
BenchmarkRBACModel                             13586 ns        13602 ns        44800
BenchmarkRBACModelSizesSmall                 2199895 ns      2197266 ns          320
BenchmarkRBACModelSizesMedium               20465481 ns     20507812 ns           32
BenchmarkRBACModelSizesLarge               206378200 ns    203125000 ns            3
BenchmarkRBACModelSmall                       117624 ns       117188 ns         5600
BenchmarkRBACModelMedium                     1077327 ns      1066767 ns          747
BenchmarkRBACModelLarge                     12209357 ns     12276786 ns           56
BenchmarkRBACModelWithResourceRoles            14148 ns        14125 ns        49778
BenchmarkRBACModelWithDomains                  19812 ns        19671 ns        37333
BenchmarkKeyMatchModel                         27553 ns        26995 ns        24889
BenchmarkRBACModelWithDeny                     16195 ns        16044 ns        44800
BenchmarkPriorityModel                         21735 ns        21484 ns        32000
BenchmarkCachedRaw                              1416 ns         1413 ns       497778
BenchmarkCachedBasicModel                        114 ns          112 ns      4480000
BenchmarkCachedRBACModel                         111 ns          112 ns      6400000
BenchmarkCachedRBACModelSmall                    114 ns          115 ns      6400000
BenchmarkCachedRBACModelMedium                   113 ns          115 ns      6400000
BenchmarkCachedRBACModelLarge                    118 ns          117 ns      6400000
BenchmarkCachedRBACModelWithResourceRoles        130 ns          129 ns      6400000
BenchmarkCachedRBACModelWithDomains              137 ns          138 ns      4977778
BenchmarkCachedKeyMatchModel                     185 ns          186 ns      3446154
BenchmarkCachedRBACModelWithDeny                 120 ns          120 ns      6400000
BenchmarkCachedPriorityModel                     115 ns          114 ns      5600000
BenchmarkVectorOperations                        114 ns          114 ns      5600000
BenchmarkHasPolicySmall                        13753 ns        13811 ns        49778
BenchmarkHasPolicyMedium                      137839 ns       138108 ns         4978
BenchmarkHasPolicyLarge                      1448342 ns      1474649 ns          498
BenchmarkAddPolicySmall                       118275 ns       115792 ns        11200
BenchmarkAddPolicyMedium                      370239 ns       371401 ns         2987
BenchmarkAddPolicyLarge                      1398158 ns      1382373 ns          373
BenchmarkRemovePolicySmall                       288 ns          285 ns      2357895
BenchmarkRemovePolicyMedium                   136928 ns       138108 ns         4978
BenchmarkRemovePolicyLarge                   1419196 ns      1411898 ns          498
BenchmarkRoleManagerSmall                       8964 ns         9068 ns        89600
BenchmarkRoleManagerMedium                     97200 ns        96257 ns         7467
BenchmarkRoleManagerLarge                    1063917 ns      1088170 ns          560
```

### CODE REVIEW

**Comment by hsluoyz** [comment]
@EmperorYP7 @sheny1xuan plz review

**Comment by hsluoyz** [comment]
> Without the support for KeyMatch4 and ABAC model in Casbin-cpp , some test cases are missing.

@cs1137195420 can you add `KeyMatch4()` to unblock Jianning here?

**Comment by cs1137195420** [comment]
> > Without the support for KeyMatch4 and ABAC model in Casbin-cpp , some test cases are missing.
> 
> @cs1137195420 can you add `KeyMatch4()` to unblock Jianning here?

Sure, I will make it.

**Comment by hsluoyz** [comment]
@EmperorYP7 @sheny1xuan plz review

**Comment by sheny1xuan** [comment]
>  I have tested on Windows, WSL, and Ubuntu. However, I encounter some errors triggered by the existing codes(only works well on Windows). I'm not sure whether it should be cared about or not.
WSL.

CI works well, I think it's will works well in local machine. I have test the latest code of master branch in ubuntu, it works well. It's caused by complier? I use `gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)` for compiling.
image
image

> In BenchmarkRBACModelSizesLarge, it takes nearly an hour to construct the test case

I have noticed this problem before, It must look deep into the implementation of RBAC. Maybe we need a new issue to fix this problem.

**Comment by JalinWang** [comment]
> > I have tested on Windows, WSL, and Ubuntu. However, I encounter some errors triggered by the existing codes(only works well on Windows). I'm not sure whether it should be cared about or not.
> > WSL.
> 
> CI works well, I think it's will works well in local machine. I have test the latest code of master branch in ubuntu, it works well. It's caused by complier? I use `gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)` for compiling. 

Weird😑
WSL: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
Ubuntu: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
Anyway, the further investment could be made when some other report.

> > In BenchmarkRBACModelSizesLarge, it takes nearly an hour to construct the test case
> 
> I have noticed this problem before, It must look deep into the implementation of RBAC. Maybe we need a new issue to fix this problem.

Okay

**Comment by JalinWang** [comment]
> 1. Without the support for `KeyMatch4` and `ABAC` model in `Casbin-cpp` , some test cases are missing.

Already add tests that are based on `KeyMatch4`.

**Pull request merged**
