### PR TITLE
chore: Update Exprtk

### PR DESCRIPTION
**Pull request by ArashPartow**
## Chore \#
chore: Update ExprTk to the lastest version.

### CODE REVIEW

**Comment by sheny1xuan** [comment]
Hi, thanks for your contributing. I have some doubts when I use exprtk. This is my code. It works well in gcc and clang, but when I complie with MSVC, It did't work. I debug this program, and find string's data in `push` function stored in stack rather than heap. This is because of the Short String Optimization.  So I must make sure the string's data is accessible in MSVC, but in gcc and clang it works well. So, I am confusing about why gcc and clang can work well. Do you have any ideas about that? @ArashPartow @EmperorYP7 

``` cpp
/*
 **************************************************************
 *         C++ Mathematical Expression Toolkit Library        *
 *                                                            *
 * Simple Example 1                                           *
 * Author: Arash Partow (1999-2022)                           *
 * URL: https://www.partow.net/programming/exprtk/index.html  *
 *                                                            *
 * Copyright notice:                                          *
 * Free use of the Mathematical Expression Toolkit Library is *
 * permitted under the guidelines and in accordance with the  *
 * most current version of the MIT License.                   *
 * http://www.opensource.org/licenses/MIT                     *
 *                                                            *
 **************************************************************
*/


#include <cstdio>
#include <string>

#include "exprtk.hpp"

using namespace std;

typedef exprtk::symbol_table<float> symbol_table_t;
typedef exprtk::expression<float>   expression_t;
typedef exprtk::parser<float>       parser_t;

symbol_table_t symbol_table;
expression_t expression;
parser_t parser;

void push(const std::string& name, const std::string& var) {
    symbol_table.add_stringvar(name, const_cast<std::string&>(var));
}

bool eval() {
    const std::string expression_string =
        "x == y";

    std::string y = "y";
    symbol_table.add_stringvar("y", y);

    expression.register_symbol_table(symbol_table);

    parser.compile(expression_string, expression);

    auto x_ptr = symbol_table.get_stringvar("x")->ref().c_str();
    auto y_ptr = symbol_table.get_stringvar("y")->ref().c_str();
    printf("x : %s\n", x_ptr);
    printf("y : %s\n", y_ptr);

    return expression.value();
}

void trig_function()
{
   push("x", "x");
   eval();
}

int main()
{
   trig_function();

   return 0;
}
```

**Comment by hsluoyz** [comment]
@ArashPartow plz fix:

image

**Comment by ArashPartow** [comment]
@sheny1xuan: I think you've nailed it. The stack variable is a _temporary_ std::string instance and as a result once the push function has returned the temporary is destroyed aka the **destructor** is called.

At that point any use of the reference to the temporary will result in **undefined behaviour** - aka cannot be relied upon regardless of compiler or std::string implementation.

As per Section 25.9 of the readme:

> The life-time of objects registered with or created from a specific symbol-table must span at least the life-time
> of the compiled expressions which utilise objects, such as variables, of that symbol-table, otherwise the result
> will be undefined behavior.

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L4307

In this case the variable passed to the symbol_table.add_stringvar method will have been **destroyed** before its use in the expression - which as noted above is **undefined behaviour**.

--------------------------------------

You have two options:

1. Ensure the variables being added to the symbol_table have a lifetime that **exceeds** the symbol_table instance

2. You can use the **symbol_table.create_variable** method to create named variables that will live for as long as the symbol_table instance exists.

**Comment by ArashPartow** [comment]
@hsluoyz  I've updated the PR description, though not sure what else needs to be done/added in order to retrigger checks.

**Comment by sheny1xuan** [comment]
> @sheny1xuan: I think you've nailed it. The stack variable is a _temporary_ std::string instance and as a result once the push function has returned the temporary is destroyed aka the **destructor** is called.
> 
> At that point any use of the reference to the temporary will result in **undefined behaviour** - aka cannot be relied upon regardless of compiler or std::string implementation.
> 
> As per Section 25.9 of the readme:
> 
> > The life-time of objects registered with or created from a specific symbol-table must span at least the life-time
> > of the compiled expressions which utilise objects, such as variables, of that symbol-table, otherwise the result
> > will be undefined behavior.
> 
> https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L4307
> 
> In this case the variable passed to the symbol_table.add_stringvar method will have been **destroyed** before its use in the expression - which as noted above is **undefined behaviour**.
> 
> You have two options:
> 
> 1. Ensure the variables being added to the symbol_table have a lifetime that **exceeds** the symbol_table instance
> 2. You can use the **symbol_table.create_variable** method to create named variables that will live for as long as the symbol_table instance exists.

Thanks for your reply, I have solved this problem using your first option. 'Undefined behaviour' makes different compiler have different result. Thank you for the explanation again.

**Comment by sheny1xuan** [comment]
> @hsluoyz I've updated the PR description, though not sure what else needs to be done/added in order to retrigger checks.

This error should is caused because of the format of commit message rather than pr message. I have updated exprtk in this [PR](https://github.com/casbin/casbin-cpp/pull/184/commits/3f627112aff21c894020f7e3d9a081182b4626cd), You can also close this PR if you don't want to change the format of commit. Thanks for your contributions.

**Comment by ArashPartow** [comment]
@sheny1xuan 
> 'Undefined behaviour' makes different compiler have different result. 

I believe that is called implementation defined behaviour.  

UB is basically where one can't assume or expect any specific or general behaviour regardless of how reasonable it may seem.

**Comment by ArashPartow** [comment]
@sheny1xuan 
> This error is caused by the format of commit message rather than pr message. 

I've updated the commit message. Hopefully the check will now pass. :crossed_fingers:

**Comment by sheny1xuan** [comment]
> @sheny1xuan
> 
> > 'Undefined behaviour' makes different compiler have different result.
> 
> I believe that is called implementation defined behaviour.
> 
> UB is basically where one can't assume or expect any specific or general behaviour regardless of how reasonable it may seem.

Very professional!

**Comment by sheny1xuan** [comment]
@ArashPartow Hi. I want to rebase a string pointer, but the expression value is fault. Do I have to do compile the expression after rebase string. This is my code. Thanks for your reply.

``` cpp
void eval() {
    const std::string expression_string =
        "r == p";

    std::string r;
    std::string p;
    symbol_table.add_stringvar("r", r);
    symbol_table.add_stringvar("p", p);

    expression.register_symbol_table(symbol_table);

    parser.compile(expression_string, expression);

    std::vector<std::string> vr = {"bob", "alice", "tom"};
    std::vector<std::string> vp = {"bob", "alice2", "tom"};

    for (size_t i = 0; i < vr.size(); i++) {
        
        symbol_table.get_stringvar("r")->rebase(vr[i]);
        symbol_table.get_stringvar("p")->rebase(vp[i]);
        // compile will work
        // parser.compile(expression_string, expression);

        auto r_ref = symbol_table.get_stringvar("r")->ref();
        auto p_ref = symbol_table.get_stringvar("p")->ref();

        printf("r : %s, p : %s \n", r_ref.c_str(), p_ref.c_str());
        printf("result: %d\n", (bool)expression.value());
    }
}
```

**Comment by sheny1xuan** [comment]
@EmperorYP7 @hsluoyz  Can you merge this PR?

**Comment by ArashPartow** [comment]
@sheny1xuan at the moment only vectors can be rebased. I'm looking to add string rebasing, but it will take some more work.

The method you've accessed is a leak in the API - only the ref() methods should have been available.

---------------

For now you'll have to assign the new values to the string variables. 

`symbol_table.get_stringvar("r")->ref() = vr[i];`

**Comment by sheny1xuan** [comment]
> @sheny1xuan at the moment only vectors can be rebased. I'm looking to add string rebasing, but it will take some more work.
> 
> The method you've accessed is a leak in the API - only the ref() methods should have been available.
> 
> For now you'll have to assign the new values to the string variables.
> 
> `symbol_table.get_stringvar("r")->ref() = vr[i];`

Yes, `ref()` works well. But using 'ref()' will copy this string, it would be inefficient. Looking forward to the feature of string rebase. @ArashPartow

**Pull request merged**
