### PR TITLE
feat: inheritance of exceptions public

### LINKED ISSUE #150: Make access to inherited exceptions public
The exceptions provide a what string that is hard to retrieve from outside the library because std::exception::what() is hidden.

Our team is wrapping the casbin-cpp with an Erlang NIF for use in Elixir and are catching the RBAC exceptions and would like to provide the what string for logging purposes on the Elixir side.

### PR DESCRIPTION
**Pull request by PolBreachIty**
## Fixes #150 

Signed-off-by: William Michaels <bill@polarity.io>

### Description

- Provide access to std::exception::what() when catching Casbin exceptions

### CODE REVIEW

**Comment by hsluoyz** [comment]
@EmperorYP7 @divy9881 plz review

**Comment by hsluoyz** [comment]
@PolBreachIty can you fix this error? https://github.com/casbin/casbin-cpp/pull/151/checks?check_run_id=3683337897

image

**Review by EmperorYP7 — APPROVED** [review]
LGTM

**Comment by EmperorYP7** [comment]
> @PolBreachIty can you fix this error? https://github.com/casbin/casbin-cpp/pull/151/checks?check_run_id=3683337897


I think this is not an error. I recently found that GH Actions is not designed to be particularly good for sustained computational work like benchmarking. (unless we pay for it, of course)

**Comment by hsluoyz** [comment]
@EmperorYP7 well explained, thanks!

**Pull request merged**
