### PR TITLE
Created Basic Policy enforcer and Tests support

### PR DESCRIPTION
**Pull request by romitkarmakar**

### CODE REVIEW

**Comment by romitkarmakar** [comment]
It uses recursive descent parser tree to evaluate the matchers string.

**Comment by romitkarmakar** [comment]
Please review this PR.

**Comment by hsluoyz** [comment]
Please name your files exactly like Go, e.g., `PolicyManager.h`, first the format will be `policy_manager.h` at least.

Second, we don't have a policy manager anywhere. Please do not invent new names.

**Comment by romitkarmakar** [comment]
Ok, I will refactor the code according to the go structure.

**Comment by hsluoyz** [comment]
Please replace wrong commits than appending them.

**Comment by hsluoyz** [comment]
Don't add a Python linter. Maybe you can use it locally, but I don't like to see it in commits.

**Comment by hsluoyz** [comment]
Don't commit so many code in one PR. One PR can only contain one commit, with 100 LoC change.

**Pull request closed without merging**
