### PR TITLE
Fully working project with RBAC, ABAC support

### PR DESCRIPTION
**Pull request by romitkarmakar**
basic policy enforcer, model adapter and built-in csv adapter has been added. Expression parsing is being done using recursive descent parsing tree as a replacement for govaluate package. Google tests has been included.

### CODE REVIEW

**Comment by romitkarmakar** [comment]
@hsluoyz review this pr.

**Comment by mnprtpsingh** [comment]
@romitkarmakar i personally feel that it will be good, if we don't create seperate a project for tests as mentioned [here](https://docs.microsoft.com/en-us/visualstudio/test/how-to-write-unit-tests-for-cpp-dlls?view=vs-2019). It will help to get all the advantages of dynamic linking/loading along with having a good coverage. What do you think about this?

**Comment by hsluoyz** [comment]
No capital letters in file names.

casbin-test instead of casbin-cpp-test

**Comment by romitkarmakar** [comment]
@techoner Thanks, I will refactor the code acccording to the go directory structure.

**Comment by romitkarmakar** [comment]
- Added google test and test cases for basic enforcement of policy.
- Removed dependencies to windows.h, so that it can get compiled in Linux. See issue: #14 
- Enforcer, Model, File adapter, Effector, RBAC, Log built See Issue #2 
- Project has been structured according to the core go lang engine.
- A custom recursive descent parser has been built to work as an alternative to the govaluate package, and the api has been kept similar with the govaluate package.

@hsluoyz , @techoner  can you review this PR ?

**Comment by romitkarmakar** [comment]
@mnprtpsingh Sorry for the late reply, I think we can also test non-exported functions in DLL by statically linking .obj files to the test project. Having a separate test folder gives us better integration testing.

**Comment by DivyPatel9881** [comment]
Nice to know, you have completed the project, but I would like to point out some missing core elements without which a user cannot use this project to the fullest.
1. ```AddFunction()``` API
2. Watcher

**Comment by DivyPatel9881** [comment]
I am afraid that your expression evaluator cannot take generic functions with different return types and different arguments. You can refer to more generic evaluators here : issue #3

**Comment by romitkarmakar** [comment]
Thanks, @DivyPatel9881. This is a MVP. I will be adding the watcher and synced enforcer in the next commit. Currently, I am working on the expression evaluator and it is still in development phase, and I will surely try to integrate generic templates and reflection into it.

**Pull request closed without merging**
