### PR TITLE
test: Benchmarks for `Model` and `RoleManager`

### PR DESCRIPTION
**Pull request by EmperorYP7**
Signed-off-by: Yash Pandey (YP) <yash.btech.cs19@iiitranchi.ac.in>

### Description

Added Benchmarks for `casbin::Model` and `casbin::RoleManager`.

### CODE REVIEW

**Comment by EmperorYP7** [comment]
@hsluoyz @xcaptain Kindly have a look

**Comment by hsluoyz** [comment]
@xcaptain

**Comment by sagilio** [comment]
@EmperorYP7 LGTM! but I find the difference between the two versions is close to at least 10x, do you know what might be the reason? 
1. c++
image
2. golang
image

**Comment by EmperorYP7** [comment]
> @EmperorYP7 LGTM! but I find the difference between the two versions is close to at least 10x, do you know what might be the reason?

@sagilio I did notice the difference right when I pushed it. As of yet, no. I am investigating it, making sure only the `Enforce()` call is benchmarked, not the `AddPolicy()` and other methods. I'll keep everyone updated on this.

**Pull request merged**
