### PR TITLE
chore: add ci for memcheck.

### LINKED ISSUE #192: [Test] Add memory check in ci.
### Description
+ Add memory check in ci to avoid memory leak or other memery question.

### PR DESCRIPTION
**Pull request by sheny1xuan**
Signed-off-by: stonex <1479765922@qq.com>

### Description
+ Add memcheck for casbin by valgrind, current code may have memory problem.
image

### CODE REVIEW

**Review by EmperorYP7 — CHANGES_REQUESTED** [review]
I think we should have a different CI workflow for Memory leaks (Valgrind) and not include it in the normal CTest workflow.

**Comment by sheny1xuan** [comment]
> I think we should have a different CI workflow for Memory leaks (Valgrind) and not include it in the normal CTest workflow.

Ok, I will separate it from CI.

**Review by EmperorYP7 — APPROVED** [review]

**Comment by EmperorYP7** [comment]
@sheny1xuan Now let's find and fix the memory leaks.

**Comment by sheny1xuan** [comment]
> @sheny1xuan Now let's find and fix the memory leaks.

Ok, will do.

**Pull request merged**
