### PR TITLE
Casbin-CPP implementation, consists of minimal implementation of every feature.

### PR DESCRIPTION
**Pull request by divy9881**
This PR consists of Config implementation, DefaultEffector implementation, Persist interface, Model implementation, RBAC policy model implementation, basic IP parser, and some basic necessary utility functions.

### CODE REVIEW

**Comment by xcaptain** [comment]
Thanks for the hard work, I will first test the config part, below are my test instructions:

```C++
// tests/config_test.cpp
#include "../src/config/Config.h"
#include <iostream>
#include <string>

using namespace std;

int main()
{
    Config cfg = Config::newConfig("tests/basic_model.conf");
    string key{"request_definition::r"};
    string r = cfg.get(key);

    cout << r << "\n";
    return 0;
}
```

makefile:

```shell
g++ -o bin/config_test src/config/Config.h tests/config_test.cpp && bin/config_test
```

and the result is:
图片

https://github.com/DivyPatel9881/casbin-cpp/blob/master/src/config/Config.h#L79
section = line.substr(1, line.length() - 1);
should -2 rather than -1.

the `Address Boundary Error` may be because the `==` sign makes `split` method fail because in `basic_model.conf` we have

```ini
[policy_effect]
e = some(where (p.eft == allow))
```

**Comment by DivyPatel9881** [comment]
Thanks for pointing out, definitely there can be a possibility of few more bugs, so my next step is to provide the tests so that I can debug my code, and provide casbin-cpp with clean code.

**Comment by hsluoyz** [comment]
Do not use cout. Use C-style first than C++ style. Actually I prefer C with class. Only string in C++ is good to use.

**Comment by DivyPatel9881** [comment]
Yeah, agreed, I know, and I have not used ```cout``` object in any of my code.

**Comment by xcaptain** [comment]
@DivyPatel9881 I can now run tests in visual studio, but the tests failed, I guess it was because of the wrong test data path.
图片

Also I found that the `const ifstream::failure e` can't catch the file not exist exception.

I found a question on stackoverflow that discuss how to construct safe file path hope that would help.
https://stackoverflow.com/questions/6297738/how-to-build-a-full-path-string-safely-from-separate-strings

**Comment by DivyPatel9881** [comment]
Thanks for pointing out because I will fix that right away.

**Comment by DivyPatel9881** [comment]
Thanks for pointing out, I will fix that right away

**Comment by DivyPatel9881** [comment]
```filesystem``` is a good option but has support C++17 onwards, so will have to take long step in order to fix this.

**Comment by xcaptain** [comment]
@DivyPatel9881 Yes, I also like the C++17 standard and <filesystem> api. Config file path is very important we need to use it to construt a model.

**Comment by DivyPatel9881** [comment]
Implementation-wise this PR is up to the mark to the core framework but may consist of bugs. I will be adding tests for the remaining modules and then it will be ready for merge.

**Comment by xcaptain** [comment]
@DivyPatel9881 Are you still working on this pull request? ZipoChan has done a lot of work recently if you want your implementation get merged first you need to hurry up :smile:

**Comment by DivyPatel9881** [comment]
Thanks @xcaptain for pointing out 😊 , my PR is ready for merge from about 20-25 days ago. The PR contains fully implemented casbin-core, just lacks testing.

**Comment by DivyPatel9881** [comment]
I thought, I will put tests, once the PR gets merged.

**Comment by xcaptain** [comment]
@DivyPatel9881 You should add tests at this pull request to make sure the current code is correct.

**Comment by divy9881** [comment]
The code-base successfully builds on VS C++ now and the code is organized according to Google guide.

**Comment by divy9881** [comment]
@hsluoyz I have fixed the linkage errors, you can now merge this PR.

**Comment by hsluoyz** [comment]
@divy9881 test still failed:

image

**Comment by divy9881** [comment]
Works fine on my PC and I have tried it on different env, again works fine. I think you should try to pull the repository again and "Rebuild the solution."

**Comment by hsluoyz** [comment]
@xcaptain can you build it?

@divy9881 we can add Azure Pipelines CI as next step, so it can be built and tested automatically on Windows.

**Comment by divy9881** [comment]
Yes, sure.

**Comment by hsluoyz** [comment]
See how we setup Azure Pipelines CI for Casbin.NET as an example if needed: https://github.com/casbin/Casbin.NET/issues/32#issuecomment-642580444

**Comment by hsluoyz** [comment]
Merged now. Raise new PRs for features/bug fix.

**Comment by divy9881** [comment]
Got it @hsluoyz

**Pull request merged**
