### PR TITLE
chore: Updated project config

### PR DESCRIPTION
**Pull request by EmperorYP7**
Signed-off-by: Yash Pandey (YP) <yash.btech.cs19@iiitranchi.ac.in>

This code:

- Changes the `CMAKE_PROJECT_NAME` to casbin and `CMAKE_PROJECT_VERSION` to 1.37.1
- Removes unnecessary installations
- Properly installs `pycasbin.so`/`pycasbin.pyd` to its desired path
- Configures include paths to be inline with the [intended client-side configuration](https://github.com/EmperorYP7/casbin-CMake-setup)

### CODE REVIEW

**Comment by hsluoyz** [comment]
@EmperorYP7 plz fix: https://github.com/casbin/casbin-cpp/pull/141/checks?check_run_id=3334833781

**Comment by hsluoyz** [comment]
@EmperorYP7 BTW, is the PyCasbin on Casbin-CPP ready for use?

**Comment by EmperorYP7** [comment]
> @EmperorYP7 BTW, is the PyCasbin on Casbin-CPP ready for use now?

Yes, it is ready for use. I exposed all of the client-side API of casbin to Python. However, `casbin::SyncedEnforcer` isn't working as expected.

**Comment by hsluoyz** [comment]
@EmperorYP7 is it available in pypi? How to use it in the code level, maybe we should provide an example.

**Comment by EmperorYP7** [comment]
> @EmperorYP7 is it available in pypi? How to use it in the code level, maybe we should provide an example.

Nope. Since the actual module is a standalone binary, it cannot be shipped with Pypi. I'll update the docs accordingly. And the usage can be figured out with the tests in `tests/python` directory.

**Comment by hsluoyz** [comment]
@EmperorYP7 how to use it in another project instead of `tests/python` folder?

**Pull request merged**
