### PR TITLE
feat: Initiated CTest setup

### LINKED ISSUE #41: Setup code coverage badge
https://dev.azure.com/Casbin/casbin/_build/results?buildId=59&view=results

image

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops

### PR DESCRIPTION
**Pull request by EmperorYP7**
### Fixes #41 Partially
Signed-off-by: Yash Pandey (YP) <yash.btech.cs19@iiitranchi.ac.in>

---
### Description

This code:
- configures the build system to install [googletest v1.11.0](https://github.com/google/googletest/tree/release-1.11.0) within `build/_deps` directory without any manual setup.
- Tests `casbin::Enforcer` and `casbin::CachedEnforcer` corresponding to the ones done in MS Unittests.
- Modifies the CI to run test script on all platforms. (ie. Linux, Windows, and Mac)

---
### Build instructions for all platforms

(Assuming you have CMake v3.19 or later installed)

1. Clone/checkout to [`EmperorYP7/casbin-cpp:ctest-setup`](https://github.com/EmperorYP7/casbin-cpp/tree/ctest-setup)
2. Open terminal/cmd in the root directory of the project:
**Note:** On Windows, this command will also create Visual Studio project files
```bash
mkdir build
cd build
cmake ..
```

3. After the project is configured successfully,
```bash
cmake --build .
```
4. To run the tests:
```bash
ctest
```

---
### Plan of action

Here's what I am working on:

- Completing all the tests and removing MS Unit Testing completely.
- Workflow for showing code coverage on pull requests/push.
- Shifting to GitHub Actions completely for CI/CD.

---
**Points to note**

- I discovered that GTest is not thread-safe. We need to work around it by joining threads before testing the result for `casbin::SyncedEnforcer` tests.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@xcaptain plz review.

**Review by EmperorYP7 — COMMENTED** [review]
@hsluoyz @xcaptain I tested this workflow on macOS Big Sur and Windows 10, it's working fine and is correctly generating VS project files in Windows. Need someone to test it on Linux. The CI is also building everything through CMake now.

**Comment by hsluoyz** [comment]
@EmperorYP7 I think the CI is Linux? Does it work?

**Comment by EmperorYP7** [comment]
@hsluoyz Yea! 
https://github.com/casbin/casbin-cpp/pull/107/checks?check_run_id=2867850214

**Comment by EmperorYP7** [comment]
@hsluoyz @xcaptain can we merge this?

**Pull request merged**
