### PR TITLE
Basic template.

### PR DESCRIPTION
**Pull request by PsiACE**
This PR provides a basic project skeleton with the following features:

- **Meson Build System**: Cross platform, easy to use, widely used in projects such as `libfuse` and `libinput`
- **Github Workflow**: 
  - Provide automatic build for mainstream platform.
  - Simple release function, only need `git tag v0.1.0` etc.

This skeleton is based on [psiace/meco](https://github.com/psiace/meco) template and has been adapted. The usage method has been put in the readme file, have a good time.

### CODE REVIEW

**Comment by PsiACE** [comment]
The purpose of providing this template is only to standardize the development process and provide assistance to some extent. I've verified on Linux that it's available.

**Comment by PsiACE** [comment]
@hsluoyz What do you think of it?

**Comment by hsluoyz** [comment]
I prefer makefile & Visual Studio project files instead of meson or CMake. And it's too early to setup GitHub workflow.

**Comment by PsiACE** [comment]
I must admit that your choice is reasonable, but I think a unified build system can help project maintainers focus, and workflows can help you identify problems early.

Of course, everything is up to you.

**Comment by hsluoyz** [comment]
See my comment here: https://github.com/casbin/casbin-cpp/issues/7

**Comment by PsiACE** [comment]
Also, I noticed that @xcaptain has shown a preference for cross-platform build tools in other people's pr.

**Comment by hsluoyz** [comment]
Please give me a pointer?

**Comment by PsiACE** [comment]
> See my comment here: #7

Got it. 

> Please give me a pointer?

https://github.com/casbin/casbin-cpp/pull/5#discussion_r388826511

**Comment by hsluoyz** [comment]
@xcaptain are you willing to be the GSoC mentor for this idea (project) if we have slot?

**Comment by xcaptain** [comment]
@hsluoyz I'm interested in this project and would like to contribute but I think I'm not capable enough as the mentor. Currently, I found a lot of people trying to contribute including @romitkarmakar @DivyPatel9881 @PsiACE  how about we work separately for some time and choose the first and best implementation as the official C++ version.

**Comment by PsiACE** [comment]
Glad to participate, the only regret is that I lack a Windows environment. (Of course, this is why I usually prefer cross-platform tools and early continuous integration)

**Comment by hsluoyz** [comment]
@xcaptain OK. I have made some commits. I think we can start from it.

@PsiACE You can add makefile to make the current enforcer code compile. Use macro to disable some Windows-specify things.

**Comment by PsiACE** [comment]
Ok, Iet me try. But maybe later.

**Pull request closed without merging**
