### PR TITLE
feat: add AddNamedMatchingFunc interface for enfocer.

### LINKED ISSUE #179: how to finish AddNamedDomainMatchingFunc' function in  using casbin-cpp,
like this :

image

### PR DESCRIPTION
**Pull request by sheny1xuan**
Signed-off-by: stonex <1479765922@qq.com>

### Description
+ add AddNamedMatchingFunc interface for enfocer.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@yuzhishuo plz review

**Comment by yuzhishuo** [comment]
> @yuzhishuo plz review

I will try the function in my project.
I really appreciate your effort. 😘

May I ask which team is responsible for the maintenance of casbin projects in China?

**Review by yuzhishuo — APPROVED** [review]

**Review by EmperorYP7 — APPROVED** [review]
LGTM

**Comment by EmperorYP7** [comment]
Thanks for confirming @yuzhishuo!

**Comment by hsluoyz** [comment]
@yuzhishuo you can join the QQ group here: https://casbin.org/en/help

**Comment by yuzhishuo** [comment]
Get it

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Yang Luo ***@***.***>
发送时间: Saturday, January 22, 2022 11:12:44 PM
收件人: casbin/casbin-cpp ***@***.***>
抄送: muduo ***@***.***>; Mention ***@***.***>
主题: Re: [casbin/casbin-cpp] feat: add AddNamedMatchingFunc interface for enfocer. (PR #182)


@yuzhishuo<https://github.com/yuzhishuo> you can join the QQ group here: https://casbin.org/en/help

―

**Pull request merged**
