### PR TITLE
feat: Implemented ABAC in Internal API

### PR DESCRIPTION
**Pull request by EmperorYP7**
Signed-off-by: Yash Pandey (YP) <yash.btech.cs19@iiitranchi.ac.in>

🚧  **Work in progress** 🚧

### CODE REVIEW

**Comment by EmperorYP7** [comment]
@xcaptain @hsluoyz May I get any snippets/implementation/pointers for ABAC workflow in internal API within casbin/casbin (GoLang)?

I tried to get into the weeds of GoLang casbin's internal API but couldn't find any nucleation spot to build this. I may also approach this from scratch, i.e. working out string manipulations to extract attributes/rules from the model and policy. But it is better to refer if it already has been worked out than to reinvent the wheel. :smile:

**Comment by EmperorYP7** [comment]
> May I get any snippets/implementation/pointers for ABAC workflow in internal API within casbin/casbin (GoLang)?
> 
> I tried to get into the weeds of GoLang casbin's internal API but couldn't find any nucleation spot to build this. I may also approach this from scratch, i.e. working out string manipulations to extract attributes/rules from the model and policy. But it is better to refer if it already has been worked out than reinventing the wheel. 😄

@hsluoyz @xcaptain

**Comment by hsluoyz** [comment]
@EmperorYP7 you can ask @closetool and @tangyang9464 , they are currently Go Casbin maintainers.

**Comment by closetool** [comment]
@EmperorYP7 I received your email, and I'm glad to help.
In casbin, ABAC relies on other project, witch you could find in https://casbin.org/docs/en/syntax-for-models#expression-evaluator.
And snippets about it: https://github.com/casbin/casbin/blob/ecc6d90bd00c77235384013a5fdfe2e7aed82e66/enforcer.go#L440.
Hope this will be helpful.

**Comment by EmperorYP7** [comment]
Closing this, continued in #122.

**Pull request closed without merging**
